#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Record a reproducible-build proof for x86_64-pc-windows-msvc.
#
# Writes deps-proof-windows-msvc.txt, which is deliberately a SEPARATE file
# from deps-proof.txt: the latter is regenerated by `make deps-proof` on
# whatever host runs it, and would overwrite a Windows section appended to it.
#
# Run from the repo root in Git Bash:
#     bash tools/repro-windows.sh
# ---------------------------------------------------------------------------
set -u

OUT=deps-proof-windows-msvc.txt

FLAGS="-C codegen-units=1 -C debuginfo=0 -C strip=symbols -C metadata=stranger-1.0.0"

# MSVC needs both of these to link deterministically:
#   /Brepro      COFF TimeDateStamp becomes a hash of the file contents
#   /DEBUG:NONE  drops the CodeView directory, whose PDB GUID is regenerated
#                per link — and which /Brepro would otherwise fold into its
#                hash, so the "deterministic" stamp varied anyway.
case "$(rustc -vV | sed -n 's/^host: //p')" in
  *windows-msvc) FLAGS="$FLAGS -C link-arg=/Brepro -C link-arg=/DEBUG:NONE" ;;
  *windows-gnu)  FLAGS="$FLAGS -C link-arg=-Wl,--no-insert-timestamp" ;;
esac

# MSYS rewrites arguments that look like Unix paths, turning /Brepro into
# C:/Program Files/Git/Brepro and failing the link with LNK1181.
export MSYS_NO_PATHCONV=1
export MSYS2_ARG_CONV_EXCL='*'

# pwd -W gives the Windows-style path a native rustc understands.
PREFIX="$(pwd -W 2>/dev/null || pwd)"

{
  echo "# Reproducible build proof — x86_64-pc-windows-msvc"
  echo "# Generated $(date -u +%Y-%m-%dT%H:%M:%SZ) by tools/repro-windows.sh"
  echo "#"
  echo "# Reproducibility is per-target. deps-proof.txt carries the Linux"
  echo "# result and the empty-manifest evidence; this file carries Windows."
  echo
  echo '$ rustc -vV'
  rustc -vV
  echo
  echo '$ flags'
  echo "$FLAGS"
  echo
  echo '$ rustc -O $FLAGS --remap-path-prefix="$(pwd -W)=." -o a.exe src/main.rs   # twice'
  rustc -O $FLAGS --remap-path-prefix="$PREFIX=." -o a.exe src/main.rs
  rustc -O $FLAGS --remap-path-prefix="$PREFIX=." -o b.exe src/main.rs
  echo
  echo "build 1: $(sha256sum a.exe | cut -d' ' -f1)"
  echo "build 2: $(sha256sum b.exe | cut -d' ' -f1)"
  if cmp -s a.exe b.exe; then
    echo "REPRODUCIBLE: byte-identical"
  else
    echo "NOT REPRODUCIBLE: $(cmp -l a.exe b.exe | wc -l) bytes differ"
  fi
  rm -f a.exe b.exe
} > "$OUT"

cat "$OUT"
echo
echo "wrote $OUT"
